// <auto-generated />
using System;
using AirSnS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AirSnS.Migrations
{
    [DbContext(typeof(AirSnSContext))]
    [Migration("20181206171325_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AirSnS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AirSnS.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AuthorityDocs");

                    b.Property<string>("CityProvince");

                    b.Property<string>("Description");

                    b.Property<string>("DistrictTown");

                    b.Property<string>("Facilities");

                    b.Property<string>("Guide");

                    b.Property<string>("Map");

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.Property<string>("PriceUnit");

                    b.Property<string>("ReturnPolicy");

                    b.Property<string>("Size");

                    b.Property<string>("Standard");

                    b.Property<string>("Type");

                    b.Property<string>("Volume");

                    b.Property<string>("WardCommune");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
